### ISSUE TITLE
Maintain `closed` state and add `isClosed` property

### ISSUE THREAD

**Issue by gmaclennan** [digidem/multi-core-indexer#21]
After the indexer is closed, it won't work any more. However currently behaviour is undefined because we don't keep a reference of the closed state. This is a non-urgent issue, because it's not causing any problems, this is just a question of completeness. Methods should throw an error once it is closed.

**Comment by gmaclennan** [comment]
Revisiting this, since the `unlink()` method requires the indexer to be closed, we should properly track the `closing` and `closed` states, and throw for other methods where relevant if `state === 'closing' || state === 'closed'` and throw for `unlink()` if `state !== 'closed'`. @EvanHahn

**Comment by EvanHahn** [comment]
Addressed in #42.
